# Уровень 0:
# Задание 1
Создайте матрицу 3 на 3, заполненную числами от 1 до 9
Прибавьте к ней матрицу с единицами на диагонале
Умножьте полученную матрицу на вектор (1, 2, 3)
Вычислить транспонированную матрицу  от полученной в результате прибавления матрицы
Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [ ]:
import numpy as np


In [ ]:
a1 = list(map(lambda x: list(range(x-2, x+1)), range(3, 10, 3)))
a1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Создайте матрицу 3 на 3, заполненную числами от 1 до 9

In [ ]:
a1 = np.arange(1, 10).reshape(3,3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Прибавьте к ней матрицу с единицами на диагонали

In [ ]:
a2 = np.identity(3)
a3 = a1+a2
a3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

Умножьте полученную матрицу на вектор (1, 2, 3)

In [ ]:
a3@np.array([1,2,3])

array([15., 34., 53.])

Вычислить транспонированную матрицу  от полученной в результате прибавления матрицы

In [ ]:
np.transpose(a3)

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [ ]:
a3.transpose()

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [ ]:
np.linalg.inv(a3)

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

# Уровень 1:
# Задание 2
Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2],
              [1, 3]])
print(m)

In [ ]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [ ]:
m1 = np.linalg.eig(m)
print('собственные значения', *m1[0], 'собственные вектора матрицы', *m1[1],   sep = '\n')

собственные значения
1.0
4.0
собственные вектора матрицы
[-0.89442719 -0.70710678]
[ 0.4472136  -0.70710678]


# Задание 3
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
a4 = np.array([[2,1,1], [1,1,1], [1,1,2]])
np.linalg.det(a4)

1.0

Добрый день, Алексей!

Спасибо за выполненное задание.

Уровень 0 - Верно!

Уровень 1 - Верно!

Отличная работа!

Зачёт!

Если остались вопросы, с удовольствием отвечу на них в личных сообщениях.

Удачи в дальнейшей учёбе!