# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [ ]:
import numpy as np
def back_arr():
  return np.array([i for i in range(int(input("give number, plz - "))-1, -1, -1)])

back_arr(), np.arange(int(input("give number, plz - "))-1,-1, -1)

give number, plz - 10
give number, plz - 10


(array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]), array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [ ]:
def BackArr(x):
    x = int(x)
    BR = np.full(x,x) - np.arange(1, x +1)
    return(BR)

def BackDiag(x):
    BD = np.diag(BackArr(x))
    return(BD)

BackDiag(int(input("give number, plz - ")))

give number, plz - 9


array([[8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

**Плохо разобрался. Пытался функцию из первого задания использовать и получаю ошибку. Переделал и всё получилось хотя функции выдают одинаковый массив. Можно ли пояснить почему так получилось**

In [ ]:
def diag_matrix():
    diag_m = np.diag((int(back_arr())))
    return(diag_m)

diag_matrix()

give number, plz - 9


TypeError: ignored

# Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [ ]:
from numpy import linalg

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

b = np.array( [ 4, 12, -3 ] )

linalg.solve(a, b), np.allclose( np.dot(a, linalg.solve(a, b)), b )

(array([ 0.46666667,  3.84444444, -5.55555556]), True)

# Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”

In [ ]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)


next_user_stats = np.array([0, 1, 2, 0, 0, 0])


def cosine( a, b ):
    
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [ ]:
my_list = []
for i in users_stats:
    my_list.append(cosine(i, next_user_stats))

print('Cамый похожий поситетель под номером', my_list.index(max(my_list)) + 1)

Cамый похожий поситетель под номером 8


# Комментарии преподавателя


Добрый вечер, спасибо за решения.
Отлично получилось.

В первом и втором заданиях как вариант можно сразу получить последовательность с помощью метода arange:

1
np.arange(N, 0, -1)

In [ ]:
np.arange(N, 0, -1)