In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [ ]:
x = np.arange(1,11) * (100 + np.random.randn(10))
y = 2 * x + np.random.randn(10)*5
X = np.vstack((x,y))
print('Мы получили 10 объектов с 2 признаками')
print(np.transpose(X))

Мы получили 10 объектов с 2 признаками
[[  98.96062377  208.49401978]
 [ 197.71106274  394.51477332]
 [ 300.56789197  593.53779036]
 [ 399.99347248  803.51427112]
 [ 494.05957612  992.6564117 ]
 [ 600.42154795 1202.37151833]
 [ 713.38001612 1419.95331948]
 [ 803.74484888 1605.74340083]
 [ 900.23019119 1801.75311964]
 [ 989.33664626 1977.62100825]]


In [ ]:
print('Матрица корреляции')
pd.DataFrame(np.transpose(X)).corr()

Матрица корреляции


0         1
0  1.000000  0.999965
1  0.999965  1.000000

In [ ]:
Xcentered = (X[0] - x.mean(), X[1] - y.mean())
m = (x.mean(), y.mean())
print('Отцентрованные признаки')
print(np.transpose(Xcentered))
print("Mean vector: ", m)

Отцентрованные признаки
[[-450.87996398 -891.5219435 ]
 [-352.129525   -705.50118996]
 [-249.27269578 -506.47817292]
 [-149.84711527 -296.50169216]
 [ -55.78101163 -107.35955158]
 [  50.5809602   102.35555505]
 [ 163.53942837  319.9373562 ]
 [ 253.90426113  505.72743755]
 [ 350.38960344  701.73715635]
 [ 439.49605852  877.60504497]]
Mean vector:  (549.8405877477815, 1100.0159632811472)


In [ ]:
covmat = np.cov(Xcentered) 
print('Матрица коваиации')
print(covmat, "\n")
print("Variance of X: ", np.cov(Xcentered)[0,0])
print("Variance of Y: ", np.cov(Xcentered)[1,1])
print("Covariance X and Y: ", np.cov(Xcentered)[0,1])

Матрица коваиации
[[ 91632.34577827 182728.6928815 ]
 [182728.6928815  364413.91504294]] 

Variance of X:  91632.34577827255
Variance of Y:  364413.91504293657
Covariance X and Y:  182728.69288149814


In [ ]:
le, vecs = np.linalg.eig(covmat)
v = vecs[:,1]
Xnew = np.dot(np.transpose(Xcentered), v)
print(f'Матрица собственных векторов:\n{vecs}\n Собственные числа:\n{le}')
print("".join(['\n']+["-" for x in range(30)]))
print(f'Так как второе собственное число гораздо больше первого,\nто для преобразования берем второй вектор:\n{v}')
print("".join(['\n']+["-" for x in range(30)]))
print(f'Преобразованные данные:\n {np.transpose(Xnew).reshape(-1,1)}')

Матрица собственных векторов:
[[-0.89391216 -0.44824218]
 [ 0.44824218 -0.89391216]]
 Собственные числа:
[5.10188039e+00 4.56041159e+05]

------------------------------
Так как второе собственное число гораздо больше первого,
то для преобразования берем второй вектор:
[-0.44824218 -0.89391216]

------------------------------
Преобразованные данные:
 [[ 999.04572331]
 [ 788.49539785]
 [ 564.48153363]
 [ 332.21426541]
 [ 120.9734108 ]
 [-114.16939507]
 [-359.30116272]
 [-565.8865051 ]
 [-784.35077621]
 [-981.5024919 ]]


In [ ]:
print( 'Как видно, матрица корреляции диагональна\nи корреляция между признаками практически равна нулю')
pd.DataFrame(np.dot(np.transpose(Xcentered), vecs)).corr()

Как видно, матрица корреляции диагональна
и корреляция между признаками практически равна нулю


0             1
0  1.000000e+00  8.985252e-16
1  8.985252e-16  1.000000e+00

In [ ]:
print('Восстановим элементы')
_= [print('Restored: ', (np.dot(Xnew[i],v) + m),': original: ', X[:,i]) for i in range(len(Xnew))]

Восстановим элементы
Restored:  [102.0261558  206.95684329] : original:  [ 98.96062377 208.49401978]
Restored:  [196.40369248 395.17033941] : original:  [197.71106274 394.51477332]
Restored:  [296.8161551  595.41905654] : original:  [300.56789197 593.53779036]
Restored:  [400.92814152 803.04559186] : original:  [399.99347248 803.51427112]
Restored:  [495.61520249 991.87636039] : original:  [494.05957612 992.6564117 ]
Restored:  [ 601.01612617 1202.07337378] : original:  [ 600.42154795 1202.37151833]
Restored:  [ 710.89452385 1421.19964157] : original:  [ 713.38001612 1419.95331948]
Restored:  [ 803.49478787 1605.86879111] : original:  [ 803.74484888 1605.74340083]
Restored:  [ 901.41968878 1801.15665947] : original:  [ 900.23019119 1801.75311964]
Restored:  [ 989.79140342 1977.3929754 ] : original:  [ 989.33664626 1977.62100825]


In [ ]:
from sklearn.decomposition import PCA

pca = PCA(n_components = 1)
XPCAreduced = pca.fit_transform(X.T)

In [ ]:
XPCAreduced

array([[ 999.04572331],
       [ 788.49539785],
       [ 564.48153363],
       [ 332.21426541],
       [ 120.9734108 ],
       [-114.16939507],
       [-359.30116272],
       [-565.8865051 ],
       [-784.35077621],
       [-981.5024919 ]])

In [ ]:
#Обратите внимание что при использовании PCA собственный вектор 
#используется со знаком минус этот момент разрешен так как любая 
#линейная комбинация собственных векторов x1, x2, ..., xm, 
#отвечающих одному и тому же собственному числу λ, является собственным 
#вектором с тем же собственным числом.

In [ ]:
for xn, x_pca in zip(Xnew, XPCAreduced):
    print(np.abs(xn), '-', np.abs(x_pca[0]), '=', np.abs(xn) - np.abs(x_pca[0]))

999.0457233085742 - 999.0457233085751 = -9.094947017729282e-13
788.4953978474407 - 788.4953978474409 = -2.2737367544323206e-13
564.4815336336583 - 564.4815336336583 = 0.0
332.21426540882067 - 332.21426540882067 = 0.0
120.97341080183106 - 120.9734108018311 = -2.842170943040401e-14
114.16939507065294 - 114.16939507065298 = -4.263256414560601e-14
359.3011627197791 - 359.3011627197793 = -2.2737367544323206e-13
565.8865051008843 - 565.8865051008845 = -2.2737367544323206e-13
784.3507762075482 - 784.3507762075485 = -3.410605131648481e-13
981.5024919014594 - 981.5024919014598 = -4.547473508864641e-13


In [ ]:
pca.inverse_transform(XPCAreduced)

array([[ 102.0261558 ,  206.95684329],
       [ 196.40369248,  395.17033941],
       [ 296.8161551 ,  595.41905654],
       [ 400.92814152,  803.04559186],
       [ 495.61520249,  991.87636039],
       [ 601.01612617, 1202.07337378],
       [ 710.89452385, 1421.19964157],
       [ 803.49478787, 1605.86879111],
       [ 901.41968878, 1801.15665947],
       [ 989.79140342, 1977.3929754 ]])

In [ ]:
print('Восстановим элементы')
_= [print('Restored: ', (pca.inverse_transform(XPCAreduced)[i]),': original: ', X[:,i]) for i in range(len(Xnew))]

Восстановим элементы
Restored:  [102.0261558  206.95684329] : original:  [ 98.96062377 208.49401978]
Restored:  [196.40369248 395.17033941] : original:  [197.71106274 394.51477332]
Restored:  [296.8161551  595.41905654] : original:  [300.56789197 593.53779036]
Restored:  [400.92814152 803.04559186] : original:  [399.99347248 803.51427112]
Restored:  [495.61520249 991.87636039] : original:  [494.05957612 992.6564117 ]
Restored:  [ 601.01612617 1202.07337378] : original:  [ 600.42154795 1202.37151833]
Restored:  [ 710.89452385 1421.19964157] : original:  [ 713.38001612 1419.95331948]
Restored:  [ 803.49478787 1605.86879111] : original:  [ 803.74484888 1605.74340083]
Restored:  [ 901.41968878 1801.15665947] : original:  [ 900.23019119 1801.75311964]
Restored:  [ 989.79140342 1977.3929754 ] : original:  [ 989.33664626 1977.62100825]


In [ ]:
pca.explained_variance_ratio_

array([0.99998881])