**Задание**

Сгенерировать последовательности, которые бы состояли из цифр (от 0 до 9)
и задавались следующим образом:

x - последовательность цифр

y1 = x1, y(i) = x(i) + x(1). Если y(i) >= 10, то y(i) = y(i) - 10

**Задача**:

научить модель предсказывать y(i) по x(i)

пробовать RNN, LSTM, GRU

**Задание 2:**

применить LSTM для решения лекционного практического задания

#Задание 1:

In [ ]:
import torch
from torch import nn
import random
import tqdm
import time

In [ ]:
tensor_10 = torch.randint(10, (1000,10))
tensor_10[0:3]

tensor([[5, 9, 6, 8, 4, 5, 2, 6, 4, 2],
        [7, 8, 0, 0, 2, 0, 5, 9, 9, 0],
        [3, 4, 5, 5, 0, 9, 2, 9, 9, 5]])

In [ ]:
tensor_40 = torch.randint(10, (1000,40))
tensor_40[0:3]

tensor([[7, 7, 7, 8, 2, 2, 4, 3, 4, 6, 5, 8, 2, 9, 8, 1, 4, 9, 3, 0, 7, 5, 6, 3,
         6, 6, 8, 3, 6, 7, 3, 2, 4, 8, 7, 9, 5, 2, 4, 5],
        [3, 0, 0, 6, 6, 8, 2, 9, 1, 1, 8, 7, 2, 6, 0, 8, 1, 7, 2, 4, 3, 4, 9, 9,
         5, 0, 5, 4, 9, 5, 2, 1, 4, 6, 5, 0, 2, 8, 3, 2],
        [2, 6, 9, 8, 7, 7, 2, 3, 4, 6, 1, 2, 3, 8, 1, 8, 5, 9, 5, 2, 1, 4, 0, 4,
         4, 2, 6, 9, 5, 5, 7, 7, 1, 0, 0, 2, 3, 8, 1, 5]])

In [ ]:
tensor_80 = torch.randint(10, (1000,80))
tensor_80[0:3]

tensor([[6, 6, 6, 9, 0, 6, 8, 5, 3, 9, 0, 9, 5, 5, 0, 7, 5, 6, 3, 3, 1, 1, 0, 6,
         0, 8, 7, 6, 5, 3, 0, 6, 2, 1, 9, 5, 4, 7, 8, 6, 3, 3, 5, 6, 0, 2, 4, 3,
         0, 1, 9, 5, 8, 6, 4, 7, 4, 9, 8, 8, 6, 4, 9, 6, 1, 1, 5, 3, 0, 2, 3, 4,
         4, 9, 7, 4, 8, 3, 6, 8],
        [6, 1, 8, 7, 2, 5, 0, 4, 0, 9, 3, 1, 6, 6, 1, 9, 0, 5, 0, 2, 6, 5, 9, 7,
         5, 2, 1, 7, 9, 0, 8, 9, 4, 6, 5, 4, 2, 3, 8, 2, 2, 6, 9, 9, 1, 4, 6, 8,
         9, 1, 4, 4, 8, 7, 0, 8, 9, 4, 6, 0, 8, 6, 8, 2, 5, 6, 9, 8, 1, 4, 6, 6,
         4, 2, 3, 2, 4, 9, 3, 4],
        [2, 7, 3, 1, 3, 0, 7, 1, 5, 2, 5, 7, 0, 3, 5, 9, 9, 7, 2, 0, 4, 7, 4, 2,
         3, 2, 5, 6, 9, 2, 2, 2, 3, 6, 7, 1, 9, 0, 2, 5, 4, 0, 6, 7, 8, 3, 8, 9,
         6, 4, 8, 9, 3, 1, 0, 5, 8, 2, 4, 4, 1, 4, 2, 4, 9, 6, 7, 1, 7, 3, 2, 5,
         0, 1, 8, 7, 3, 4, 1, 6]])

In [ ]:
def transform(tensor):
    y = torch.zeros_like(tensor)
    for j in range(len(y)):
        for i in range(len(y[1,:])):
            y[j,0] = tensor[j,0]
            #y[j,i] = (y[j,i-1]+tensor[j,i]) % 10
            y[j,i] = (tensor[j,i]+y[j,0]) % 10
    return y

In [ ]:
transform_tensor_10 = transform(tensor_10)
tensor_10[:3], transform_tensor_10[:3]

(tensor([[5, 9, 6, 8, 4, 5, 2, 6, 4, 2],
         [7, 8, 0, 0, 2, 0, 5, 9, 9, 0],
         [3, 4, 5, 5, 0, 9, 2, 9, 9, 5]]),
 tensor([[5, 4, 1, 3, 9, 0, 7, 1, 9, 7],
         [7, 5, 7, 7, 9, 7, 2, 6, 6, 7],
         [3, 7, 8, 8, 3, 2, 5, 2, 2, 8]]))

In [ ]:
transform_tensor_40 = transform(tensor_40)
tensor_40[:3], transform_tensor_40[:3]

(tensor([[7, 7, 7, 8, 2, 2, 4, 3, 4, 6, 5, 8, 2, 9, 8, 1, 4, 9, 3, 0, 7, 5, 6, 3,
          6, 6, 8, 3, 6, 7, 3, 2, 4, 8, 7, 9, 5, 2, 4, 5],
         [3, 0, 0, 6, 6, 8, 2, 9, 1, 1, 8, 7, 2, 6, 0, 8, 1, 7, 2, 4, 3, 4, 9, 9,
          5, 0, 5, 4, 9, 5, 2, 1, 4, 6, 5, 0, 2, 8, 3, 2],
         [2, 6, 9, 8, 7, 7, 2, 3, 4, 6, 1, 2, 3, 8, 1, 8, 5, 9, 5, 2, 1, 4, 0, 4,
          4, 2, 6, 9, 5, 5, 7, 7, 1, 0, 0, 2, 3, 8, 1, 5]]),
 tensor([[7, 4, 4, 5, 9, 9, 1, 0, 1, 3, 2, 5, 9, 6, 5, 8, 1, 6, 0, 7, 4, 2, 3, 0,
          3, 3, 5, 0, 3, 4, 0, 9, 1, 5, 4, 6, 2, 9, 1, 2],
         [3, 3, 3, 9, 9, 1, 5, 2, 4, 4, 1, 0, 5, 9, 3, 1, 4, 0, 5, 7, 6, 7, 2, 2,
          8, 3, 8, 7, 2, 8, 5, 4, 7, 9, 8, 3, 5, 1, 6, 5],
         [2, 8, 1, 0, 9, 9, 4, 5, 6, 8, 3, 4, 5, 0, 3, 0, 7, 1, 7, 4, 3, 6, 2, 6,
          6, 4, 8, 1, 7, 7, 9, 9, 3, 2, 2, 4, 5, 0, 3, 7]]))

In [ ]:
transform_tensor_80 = transform(tensor_80)
tensor_80[:3], transform_tensor_80[:3]

(tensor([[6, 6, 6, 9, 0, 6, 8, 5, 3, 9, 0, 9, 5, 5, 0, 7, 5, 6, 3, 3, 1, 1, 0, 6,
          0, 8, 7, 6, 5, 3, 0, 6, 2, 1, 9, 5, 4, 7, 8, 6, 3, 3, 5, 6, 0, 2, 4, 3,
          0, 1, 9, 5, 8, 6, 4, 7, 4, 9, 8, 8, 6, 4, 9, 6, 1, 1, 5, 3, 0, 2, 3, 4,
          4, 9, 7, 4, 8, 3, 6, 8],
         [6, 1, 8, 7, 2, 5, 0, 4, 0, 9, 3, 1, 6, 6, 1, 9, 0, 5, 0, 2, 6, 5, 9, 7,
          5, 2, 1, 7, 9, 0, 8, 9, 4, 6, 5, 4, 2, 3, 8, 2, 2, 6, 9, 9, 1, 4, 6, 8,
          9, 1, 4, 4, 8, 7, 0, 8, 9, 4, 6, 0, 8, 6, 8, 2, 5, 6, 9, 8, 1, 4, 6, 6,
          4, 2, 3, 2, 4, 9, 3, 4],
         [2, 7, 3, 1, 3, 0, 7, 1, 5, 2, 5, 7, 0, 3, 5, 9, 9, 7, 2, 0, 4, 7, 4, 2,
          3, 2, 5, 6, 9, 2, 2, 2, 3, 6, 7, 1, 9, 0, 2, 5, 4, 0, 6, 7, 8, 3, 8, 9,
          6, 4, 8, 9, 3, 1, 0, 5, 8, 2, 4, 4, 1, 4, 2, 4, 9, 6, 7, 1, 7, 3, 2, 5,
          0, 1, 8, 7, 3, 4, 1, 6]]),
 tensor([[6, 2, 2, 5, 6, 2, 4, 1, 9, 5, 6, 5, 1, 1, 6, 3, 1, 2, 9, 9, 7, 7, 6, 2,
          6, 4, 3, 2, 1, 9, 6, 2, 8, 7, 5, 1, 0, 3, 4, 2, 9, 9, 1, 2, 6, 

In [ ]:
BATCH_SIZE = 128
dataset_10 = torch.utils.data.TensorDataset(tensor_10, transform_tensor_10)
data_10 = torch.utils.data.DataLoader(dataset_10, BATCH_SIZE, shuffle=True)

dataset_40 = torch.utils.data.TensorDataset(tensor_40, transform_tensor_40)
data_40 = torch.utils.data.DataLoader(dataset_40, BATCH_SIZE, shuffle=True)

dataset_80 = torch.utils.data.TensorDataset(tensor_80, transform_tensor_80)
data_80 = torch.utils.data.DataLoader(dataset_80, BATCH_SIZE, shuffle=True)

In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self, rnnClass, dictionary_size, embedding_size, num_hiddens, num_classes):
        super().__init__()

        self.embedding = nn.Embedding(dictionary_size, embedding_size)
        self.hidden = rnnClass(embedding_size, num_hiddens, batch_first=True)
        self.output = nn.Linear(num_hiddens, num_classes)

    def forward(self, X):
        out = self.embedding(X)
        #_, state = self.hidden(out)
        #predictions = self.output(state[0])
        out, state = self.hidden(out)
        predictions = self.output(out)
        if isinstance(self.hidden, nn.LSTM):
            predictions = predictions.squeeze(0)
        return predictions

In [ ]:
def train_model(model, loader, n_epochs):
    train_losses = []
    #train_accuracy = []
    criterion = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=0.05)

    for epoch in range(1, n_epochs + 1):
        start = time.time()
        train_loss, train_acc, n = 0.0, 0.0, 0

        model.train()
        for X, y in loader:
            optimizer.zero_grad()
            y_pred = model.forward(X)
            loss = criterion(y_pred, y)#.float())
            train_loss += loss.item()
            train_acc += (y_pred.argmax(dim=1) == y).sum().item()
            n += y.shape[0]*y.shape[1]
            loss.backward()
            optimizer.step()

        train_loss /= len(loader)
        train_losses.append(train_loss)
        sec = time.time() - start
        stat = f'Epoch: {epoch}, time: {sec:.1f}s, loss: {train_loss:.3f}, acc:{train_acc/n:.3f} '
        if (epoch) % 200 == 0:
            print(stat)


    return model, train_losses

In [ ]:
embedding_size = 64
num_hiddens = 128
n_epochs = 3000

In [ ]:
model_RNN_10 = NeuralNetwork(nn.RNN, 10 , embedding_size, num_hiddens, 10)
model, train_losses = train_model(model_RNN_10, data_10, n_epochs)

Epoch: 200, time: 0.1s, loss: 2.080, acc:0.219 
Epoch: 400, time: 0.1s, loss: 1.945, acc:0.303 
Epoch: 600, time: 0.1s, loss: 1.764, acc:0.387 
Epoch: 800, time: 0.1s, loss: 1.560, acc:0.469 
Epoch: 1000, time: 0.1s, loss: 1.354, acc:0.549 
Epoch: 1200, time: 0.1s, loss: 1.159, acc:0.624 
Epoch: 1400, time: 0.1s, loss: 0.974, acc:0.695 
Epoch: 1600, time: 0.1s, loss: 0.824, acc:0.751 
Epoch: 1800, time: 0.1s, loss: 0.688, acc:0.801 
Epoch: 2000, time: 0.1s, loss: 0.567, acc:0.845 
Epoch: 2200, time: 0.1s, loss: 0.481, acc:0.869 
Epoch: 2400, time: 0.1s, loss: 0.405, acc:0.894 
Epoch: 2600, time: 0.1s, loss: 0.359, acc:0.906 
Epoch: 2800, time: 0.1s, loss: 0.313, acc:0.916 
Epoch: 3000, time: 0.1s, loss: 0.283, acc:0.924 


In [ ]:
model_RNN_40 = NeuralNetwork(nn.RNN, 40, embedding_size, num_hiddens, 40)
model, train_losses = train_model(model_RNN_40, data_40, n_epochs)

Epoch: 200, time: 0.3s, loss: 2.344, acc:0.117 
Epoch: 400, time: 0.3s, loss: 2.310, acc:0.130 
Epoch: 600, time: 0.2s, loss: 2.277, acc:0.134 
Epoch: 800, time: 0.3s, loss: 2.264, acc:0.143 
Epoch: 1000, time: 0.2s, loss: 2.251, acc:0.151 
Epoch: 1200, time: 0.3s, loss: 2.241, acc:0.157 
Epoch: 1400, time: 0.3s, loss: 2.231, acc:0.163 
Epoch: 1600, time: 0.3s, loss: 2.222, acc:0.170 
Epoch: 1800, time: 0.3s, loss: 2.216, acc:0.174 
Epoch: 2000, time: 0.3s, loss: 2.208, acc:0.179 
Epoch: 2200, time: 0.2s, loss: 2.201, acc:0.183 
Epoch: 2400, time: 0.3s, loss: 2.192, acc:0.187 
Epoch: 2600, time: 0.2s, loss: 2.185, acc:0.192 
Epoch: 2800, time: 0.2s, loss: 2.178, acc:0.197 
Epoch: 3000, time: 0.4s, loss: 2.172, acc:0.199 


In [ ]:
model_RNN_80 = NeuralNetwork(nn.RNN, 80, embedding_size, num_hiddens, 80)
model, train_losses = train_model(model_RNN_80, data_80, n_epochs)

Epoch: 200, time: 0.5s, loss: 2.343, acc:0.112 
Epoch: 400, time: 0.6s, loss: 2.311, acc:0.118 
Epoch: 600, time: 0.6s, loss: 2.294, acc:0.125 
Epoch: 800, time: 0.8s, loss: 2.288, acc:0.131 
Epoch: 1000, time: 0.5s, loss: 2.283, acc:0.136 
Epoch: 1200, time: 0.5s, loss: 2.279, acc:0.138 
Epoch: 1400, time: 0.6s, loss: 2.275, acc:0.142 
Epoch: 1600, time: 0.6s, loss: 2.271, acc:0.145 
Epoch: 1800, time: 0.5s, loss: 2.267, acc:0.147 
Epoch: 2000, time: 0.6s, loss: 2.263, acc:0.150 
Epoch: 2200, time: 0.6s, loss: 2.259, acc:0.153 
Epoch: 2400, time: 1.0s, loss: 2.255, acc:0.156 
Epoch: 2600, time: 0.5s, loss: 2.251, acc:0.159 
Epoch: 2800, time: 0.5s, loss: 2.247, acc:0.161 
Epoch: 3000, time: 0.5s, loss: 2.243, acc:0.163 


In [ ]:
model_GRU_10 = NeuralNetwork(nn.GRU, 10, embedding_size, num_hiddens, 10)
model, train_losses = train_model(model_GRU_10, data_10, n_epochs)

Epoch: 200, time: 0.2s, loss: 2.288, acc:0.129 
Epoch: 400, time: 0.1s, loss: 2.275, acc:0.139 
Epoch: 600, time: 0.2s, loss: 2.255, acc:0.153 
Epoch: 800, time: 0.1s, loss: 2.225, acc:0.167 
Epoch: 1000, time: 0.2s, loss: 2.168, acc:0.188 
Epoch: 1200, time: 0.1s, loss: 2.031, acc:0.249 
Epoch: 1400, time: 0.2s, loss: 1.921, acc:0.293 
Epoch: 1600, time: 0.2s, loss: 1.833, acc:0.330 
Epoch: 1800, time: 0.3s, loss: 1.738, acc:0.370 
Epoch: 2000, time: 0.3s, loss: 1.633, acc:0.420 
Epoch: 2200, time: 0.2s, loss: 1.514, acc:0.470 
Epoch: 2400, time: 0.2s, loss: 1.387, acc:0.519 
Epoch: 2600, time: 0.2s, loss: 1.251, acc:0.577 
Epoch: 2800, time: 0.2s, loss: 1.108, acc:0.640 
Epoch: 3000, time: 0.2s, loss: 0.961, acc:0.698 


In [ ]:
model_GRU_40 = NeuralNetwork(nn.GRU, 40, embedding_size, num_hiddens, 40)
model, train_losses = train_model(model_GRU_40, data_40, n_epochs)

Epoch: 200, time: 0.7s, loss: 2.398, acc:0.108 
Epoch: 400, time: 0.6s, loss: 2.354, acc:0.113 
Epoch: 600, time: 0.6s, loss: 2.317, acc:0.117 
Epoch: 800, time: 0.6s, loss: 2.300, acc:0.122 
Epoch: 1000, time: 0.6s, loss: 2.291, acc:0.127 
Epoch: 1200, time: 0.7s, loss: 2.285, acc:0.131 
Epoch: 1400, time: 0.7s, loss: 2.280, acc:0.136 
Epoch: 1600, time: 0.6s, loss: 2.273, acc:0.138 
Epoch: 1800, time: 0.6s, loss: 2.268, acc:0.143 
Epoch: 2000, time: 0.7s, loss: 2.262, acc:0.146 
Epoch: 2200, time: 0.6s, loss: 2.255, acc:0.150 
Epoch: 2400, time: 0.9s, loss: 2.249, acc:0.154 
Epoch: 2600, time: 0.6s, loss: 2.242, acc:0.157 
Epoch: 2800, time: 0.9s, loss: 2.235, acc:0.163 
Epoch: 3000, time: 0.7s, loss: 2.227, acc:0.167 


In [ ]:
model_GRU_80 = NeuralNetwork(nn.GRU, 80, embedding_size, num_hiddens, 80)
model, train_losses = train_model(model_GRU_80, data_80, n_epochs)

Epoch: 200, time: 1.3s, loss: 2.469, acc:0.105 
Epoch: 400, time: 1.4s, loss: 2.385, acc:0.108 
Epoch: 600, time: 1.3s, loss: 2.336, acc:0.114 
Epoch: 800, time: 1.3s, loss: 2.317, acc:0.116 
Epoch: 1000, time: 1.3s, loss: 2.307, acc:0.117 
Epoch: 1200, time: 1.9s, loss: 2.300, acc:0.120 
Epoch: 1400, time: 1.5s, loss: 2.296, acc:0.124 
Epoch: 1600, time: 1.3s, loss: 2.293, acc:0.126 
Epoch: 1800, time: 1.3s, loss: 2.291, acc:0.129 
Epoch: 2000, time: 1.4s, loss: 2.289, acc:0.130 
Epoch: 2200, time: 1.3s, loss: 2.286, acc:0.132 
Epoch: 2400, time: 1.4s, loss: 2.284, acc:0.134 
Epoch: 2600, time: 2.0s, loss: 2.282, acc:0.136 
Epoch: 2800, time: 1.3s, loss: 2.280, acc:0.137 
Epoch: 3000, time: 1.3s, loss: 2.278, acc:0.139 


In [ ]:
model_LSTM_10 = NeuralNetwork(nn.LSTM, 10, embedding_size, num_hiddens, 10)
model, train_losses = train_model(model_LSTM_10, data_10, n_epochs)

Epoch: 200, time: 0.2s, loss: 2.294, acc:0.120 
Epoch: 400, time: 0.2s, loss: 2.289, acc:0.125 
Epoch: 600, time: 0.2s, loss: 2.283, acc:0.131 
Epoch: 800, time: 0.2s, loss: 2.270, acc:0.135 
Epoch: 1000, time: 0.2s, loss: 2.242, acc:0.150 
Epoch: 1200, time: 0.2s, loss: 2.171, acc:0.179 
Epoch: 1400, time: 0.2s, loss: 2.057, acc:0.234 
Epoch: 1600, time: 0.2s, loss: 1.962, acc:0.279 
Epoch: 1800, time: 0.2s, loss: 1.861, acc:0.315 
Epoch: 2000, time: 0.2s, loss: 1.755, acc:0.366 
Epoch: 2200, time: 0.2s, loss: 1.646, acc:0.423 
Epoch: 2400, time: 0.2s, loss: 1.531, acc:0.471 
Epoch: 2600, time: 0.2s, loss: 1.407, acc:0.520 
Epoch: 2800, time: 0.2s, loss: 1.272, acc:0.578 
Epoch: 3000, time: 0.2s, loss: 1.148, acc:0.628 


In [ ]:
model_LSTM_40 = NeuralNetwork(nn.LSTM, 40, embedding_size, num_hiddens, 40)
model, train_losses = train_model(model_LSTM_40, data_40, n_epochs)

Epoch: 200, time: 0.9s, loss: 2.424, acc:0.104 
Epoch: 400, time: 0.7s, loss: 2.360, acc:0.109 
Epoch: 600, time: 0.9s, loss: 2.330, acc:0.118 
Epoch: 800, time: 0.7s, loss: 2.308, acc:0.119 
Epoch: 1000, time: 0.7s, loss: 2.305, acc:0.125 
Epoch: 1200, time: 0.9s, loss: 2.293, acc:0.127 
Epoch: 1400, time: 0.7s, loss: 2.285, acc:0.132 
Epoch: 1600, time: 0.8s, loss: 2.279, acc:0.134 
Epoch: 1800, time: 0.7s, loss: 2.273, acc:0.140 
Epoch: 2000, time: 0.7s, loss: 2.266, acc:0.144 
Epoch: 2200, time: 0.8s, loss: 2.260, acc:0.149 
Epoch: 2400, time: 0.9s, loss: 2.254, acc:0.153 
Epoch: 2600, time: 1.1s, loss: 2.246, acc:0.157 
Epoch: 2800, time: 0.7s, loss: 2.236, acc:0.163 
Epoch: 3000, time: 0.8s, loss: 2.229, acc:0.166 


In [ ]:
model_LSTM_80 = NeuralNetwork(nn.LSTM, 80, embedding_size, num_hiddens, 80)
model, train_losses = train_model(model_LSTM_80, data_80, n_epochs)

Epoch: 200, time: 1.6s, loss: 2.411, acc:0.101 
Epoch: 400, time: 1.7s, loss: 2.359, acc:0.106 
Epoch: 600, time: 1.7s, loss: 2.329, acc:0.112 
Epoch: 800, time: 1.7s, loss: 2.317, acc:0.112 
Epoch: 1000, time: 1.5s, loss: 2.311, acc:0.114 
Epoch: 1200, time: 1.6s, loss: 2.305, acc:0.117 
Epoch: 1400, time: 1.7s, loss: 2.301, acc:0.119 
Epoch: 1600, time: 1.8s, loss: 2.298, acc:0.122 
Epoch: 1800, time: 1.5s, loss: 2.295, acc:0.123 
Epoch: 2000, time: 2.5s, loss: 2.293, acc:0.125 
Epoch: 2200, time: 2.1s, loss: 2.291, acc:0.128 
Epoch: 2400, time: 1.5s, loss: 2.289, acc:0.129 
Epoch: 2600, time: 1.6s, loss: 2.287, acc:0.131 
Epoch: 2800, time: 1.5s, loss: 2.285, acc:0.133 
Epoch: 3000, time: 1.6s, loss: 2.283, acc:0.135 


#Задание 2

In [ ]:
!wget https://s3.amazonaws.com/text-datasets/nietzsche.txt

--2023-06-10 11:29:59--  https://s3.amazonaws.com/text-datasets/nietzsche.txt
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.128.165, 52.217.254.32, 52.216.25.54, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.128.165|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 600901 (587K) [text/plain]
Saving to: ‘nietzsche.txt’

nietzsche.txt       100%[===================>] 586.82K  --.-KB/s    in 0.04s   

2023-06-10 11:29:59 (13.7 MB/s) - ‘nietzsche.txt’ saved [600901/600901]



In [ ]:
import re

In [ ]:
with open('nietzsche.txt', encoding='utf-8') as f:
    text = f.read().lower()
print('length:', len(text))
text = re.sub('[^a-z ]', ' ', text)
text = re.sub('\s+', ' ', text)

length: 600893


In [ ]:
text[:100]

'preface supposing that truth is a woman what then is there not ground for suspecting that all philos'

In [ ]:
INDEX_TO_CHAR = sorted(list(set(text)))
CHAR_TO_INDEX = {c: i for i, c in enumerate(INDEX_TO_CHAR)}
CHAR_TO_INDEX

{' ': 0,
 'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26}

In [ ]:
MAX_LEN = 40
STEP = 3
SENTENCES = []
NEXT_CHARS = []
for i in range(0, len(text) - MAX_LEN, STEP):
    SENTENCES.append(text[i: i + MAX_LEN])
    NEXT_CHARS.append(text[i + MAX_LEN])
print('Num sents:', len(SENTENCES))

Num sents: 193075


In [ ]:
print('Vectorization...')
X = torch.zeros((len(SENTENCES), MAX_LEN), dtype=int)
Y = torch.zeros((len(SENTENCES)), dtype=int)
for i, sentence in enumerate(SENTENCES):
    for t, char in enumerate(sentence):
        X[i, t] = CHAR_TO_INDEX[char]
    Y[i] = CHAR_TO_INDEX[NEXT_CHARS[i]]

Vectorization...


In [ ]:
X[0:1], Y[0]

(tensor([[16, 18,  5,  6,  1,  3,  5,  0, 19, 21, 16, 16, 15, 19,  9, 14,  7,  0,
          20,  8,  1, 20,  0, 20, 18, 21, 20,  8,  0,  9, 19,  0,  1,  0, 23, 15,
          13,  1, 14,  0]]),
 tensor(23))

In [ ]:
BATCH_SIZE=512
dataset = torch.utils.data.TensorDataset(X, Y)
data = torch.utils.data.DataLoader(dataset, BATCH_SIZE, shuffle=True)

In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self, rnnClass, dictionary_size, embedding_size, num_hiddens, num_classes):
        super().__init__()

        self.num_hiddens = num_hiddens
        self.embedding = nn.Embedding(dictionary_size, embedding_size)
        self.hidden = rnnClass(embedding_size, num_hiddens, batch_first=True)
        self.output = nn.Linear(num_hiddens, num_classes)

    def forward(self, X):
        out = self.embedding(X)
        _, state = self.hidden(out)
        predictions = self.output(state[0])
        return predictions.squeeze(0)

In [ ]:
model = NeuralNetwork(nn.LSTM, len(CHAR_TO_INDEX), 64, 128, len(CHAR_TO_INDEX))

In [ ]:
model(X[0:1])

tensor([[ 0.1459,  0.0355, -0.0978, -0.0496, -0.1056,  0.0474, -0.1334,  0.0601,
         -0.0025,  0.0507, -0.1464,  0.0236, -0.0415, -0.1619,  0.2169, -0.0908,
          0.1089, -0.0185, -0.0636, -0.0202, -0.0546, -0.0110,  0.0126,  0.1513,
          0.1650, -0.1466, -0.0345]], grad_fn=<SqueezeBackward1>)

In [ ]:
def sample(preds):
    softmaxed = torch.softmax(preds, 0)
    probas = torch.distributions.multinomial.Multinomial(1, softmaxed).sample()
    return probas.argmax()

def generate_text():
    start_index = random.randint(0, len(text) - MAX_LEN - 1)

    generated = ''
    sentence = text[start_index: start_index + MAX_LEN]
    generated += sentence

    for i in range(MAX_LEN):
        x_pred = torch.zeros((1, MAX_LEN), dtype=int)
        for t, char in enumerate(generated[-MAX_LEN:]):
            x_pred[0, t] = CHAR_TO_INDEX[char]

        preds = model(x_pred)[0]
        next_char = INDEX_TO_CHAR[sample(preds)]
        generated = generated + next_char

    print(generated[:MAX_LEN] + '|' + generated[MAX_LEN:])

In [ ]:
generate_text()

leasure or avoid pain in any sense it is|vrfdxxhrsgxelyfhxlcazpipbesrxos mlfwlves


In [ ]:
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters())

In [ ]:
for ep in range(5):
    start = time.time()
    train_loss = 0.
    train_passed = 0

    model.train()
    for X_b, y_b in tqdm.tqdm_notebook(data):
        X_b, y_b = X_b, y_b
        optimizer.zero_grad()
        answers = model.forward(X_b)
        loss = criterion(answers, y_b)
        train_loss += loss.item()

        loss.backward()
        optimizer.step()
        train_passed += 1

    print("Epoch {}. Time: {:.3f}, Train loss: {:.3f}".format(ep, time.time() - start, train_loss / train_passed))
    model.eval()
    generate_text()

<ipython-input-43-8f474e72f798>:7: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for X_b, y_b in tqdm.tqdm_notebook(data):


  0%|          | 0/378 [00:00<?, ?it/s]

Epoch 0. Time: 153.915, Train loss: 2.163
ars to find out who the garden god epicu|ouse in one munssess of filof mat in ofs


  0%|          | 0/378 [00:00<?, ?it/s]

Epoch 1. Time: 158.351, Train loss: 1.783
ult situations and entertainment amid a |swicetuous s whivhe here the spirly the 


  0%|          | 0/378 [00:00<?, ?it/s]

Epoch 2. Time: 156.130, Train loss: 1.646
ve and impartial eye of an epicurean god|er opres as ill is finst and sruit and l


  0%|          | 0/378 [00:00<?, ?it/s]

Epoch 3. Time: 153.787, Train loss: 1.563
without love with unfathomable eyes wet |as has becaper courst not severalo nast 


  0%|          | 0/378 [00:00<?, ?it/s]

Epoch 4. Time: 153.301, Train loss: 1.504
 truth from the very first nothing is mo|ss nou othest on thray relests to han po
